stock_data_backtesting:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres_dwh  
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      schema: public
      threads: 4
