stock_data_backtesting:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres_dwh  
      port: 5432
      user: postgres
      password: postgres
      dbname: postgres_dwh
      schema: public
      threads: 4
