airflow:
  core:
    parallelism: 64
    max_active_runs_per_dag: 32
    max_active_tasks_per_dag: 64

  scheduler:
    dag_dir_list_interval: 30
    min_file_process_interval: 30
  
  pools:
    - name: api_pool
      slots: 32
      description: "Pool for controlling API-heavy tasks"
